test_profile:
  target: dev
  outputs:
    dev:
      type: postgres
      host: 192.168.65.254
      user: potey
      password: lazlo
      port: 5432
      dbname: laz
      schema: public
      threads: 1
